"""
Perform MAP-Elites iterations.

Generates Parsec Coordinates to check if sample satisfies constrains
Only such "valid" samples are evaluated and added to the archive.

    - non-intersecting polynomials, 
    - non-negative y-values for upper polynomial
    - more than 1 local optimum for upper polynomial 

Candidate solutions are generated by a custom emitter class, which
adds Gaussian Noise scaled to the boundaries of solution space.

These samples are then evaluated on their
respective target objective function. 

For SAIL these are
    - Acquisition Values
    - Prediction Values



In order to generalize this function for problem domains
different than XFOIL, the generate_parsec_coordinates()
function and the codeblock checking for validity can be
removed.
"""


###### Import packages #####
from ribs.schedulers import Scheduler
from ribs.emitters import GaussianEmitter
from ribs.emitters._emitter_base import EmitterBase
from acq_functions.acq_ucb import acq_ucb
from tqdm import tqdm
import numpy as np
import time

##### Import custom scripts #####
from xfoil.generate_airfoils import generate_parsec_coordinates
from gp.predict_objective import predict_objective
from utils.pprint_nd import pprint

from config.config import Config
config = Config('config/config.ini')
TEST_RUNS = config.TEST_RUNS
BATCH_SIZE = config.BATCH_SIZE
SIGMA_EMITTER = config.SIGMA_EMITTER
SOL_DIMENSION = config.SOL_DIMENSION
SOL_VALUE_RANGE = config.SOL_VALUE_RANGE
BHV_VALUE_RANGE = config.BHV_VALUE_RANGE
ACQ_N_MAP_EVALS = config.ACQ_N_MAP_EVALS
PRED_N_MAP_EVALS = config.PRED_N_MAP_EVALS
OBJ_BHV_NUMBER_BINS = config.OBJ_BHV_NUMBER_BINS
ACQ_BHV_NUMBER_BINS = config.ACQ_BHV_NUMBER_BINS
PREDICTION_VERIFICATIONS = config.PREDICTION_VERIFICATIONS

def map_elites(self, target_archive, acq_flag=False, pred_flag=False):

    print("\n\nInitialize Map-Elites [...]")
    gp_model = self.gp_model
    target = "Acquisition" if acq_flag else "Prediction"

    if acq_flag:
        target_function = acq_ucb
        n_evals = ACQ_N_MAP_EVALS*10

    if pred_flag:
        target_function = predict_objective
        n_evals = PRED_N_MAP_EVALS

    obj_elite_df = self.obj_archive.as_pandas(include_solutions=True)
    target_archive_df = target_archive.as_pandas(include_solutions=True)
    target_archive.clear()
    target_archive.add(obj_elite_df.solution_batch(), obj_elite_df.objective_batch(), obj_elite_df.measures_batch())
    if self.custom_flag:
        self.update_archive(candidate_sol=target_archive_df.solution_batch(), candidate_bhv=target_archive_df.measures_batch(), acq_flag=acq_flag, pred_flag=pred_flag)

    print(f"Best {target} Objective: ", target_archive.as_pandas(include_solutions=True).sort_values(by='objective', ascending=False).head(1).objective_batch())
    print(f"Worst {target} Objective: ", target_archive.as_pandas(include_solutions=True).sort_values(by='objective', ascending=False).tail(1).objective_batch())

    remaining_evals = n_evals
    total_iterations = remaining_evals // BATCH_SIZE

    size_t0 = target_archive.stats.num_elites
    print(f"{target} Size: ", str(size_t0))

    start_time = time.time()

    with tqdm(total=total_iterations) as progress:
        while((remaining_evals-BATCH_SIZE >= 0)):

            progress.update(1)

            sigma_emitter = SIGMA_EMITTER + 0.25*(remaining_evals/n_evals)
            emitter = update_emitter(self, target_archive=target_archive, sigma_emitter=sigma_emitter)
            scheduler = _Scheduler(target_archive, emitter)

            # Create Samples
            samples = scheduler.ask()

            # Generate Parsec Coordinates
            valid_indices, _ = generate_parsec_coordinates(samples=samples, io_flag=False)
            samples = samples[valid_indices]

            # Calculate Acquisitions/Predictions
            scheduler_bhv = samples[:,1:3]  # ToDO: generalize calculate_behavior()
            candidate_sol = samples
            candidate_obj = target_function(self=self, genomes=candidate_sol, gp_model=gp_model)
            candidate_bhv = scheduler_bhv

            target_archive.add(solution_batch=candidate_sol, objective_batch=candidate_obj, measures_batch=candidate_bhv)
            remaining_evals -= BATCH_SIZE

    # calculate anytime stats
    size_t1 = target_archive.stats.num_elites
    print(f"\n{target} Size: ", str(size_t1))
    print("[...] End Map-Elites\n\n")
    if self.acq_mes_flag and acq_flag: self.mes_sobol_cellgrids = None # free RAM
    return size_t0, size_t1


def update_emitter(self, target_archive, sigma_emitter=SIGMA_EMITTER, sol_value_range=SOL_VALUE_RANGE):

    self.update_seed()

    emitter = [
        ScaledGaussianEmitter(
        archive=target_archive,
        sigma=sigma_emitter,
        bounds= np.array(sol_value_range),
        batch_size=BATCH_SIZE,
        seed=self.current_seed
    )]

    return emitter


class ScaledGaussianEmitter(GaussianEmitter):

    """
    Custom Emitter class
        - Adds Gaussian Noise scaled to solution space boundaries
        - Requires filled archive instead of initial solutions
    """

    def __init__(self,
                 archive,
                 *,
                 sigma,
                 bounds=None,
                 batch_size=BATCH_SIZE,
                 seed=None):

        self._rng = np.random.default_rng(seed)
        self._batch_size = batch_size
        self._sigma = np.array(sigma, dtype=archive.dtype)

        if archive.stats.num_elites == 0:
            raise ValueError("Archive must be filled with initial solutions.")

        EmitterBase.__init__(
            self,
            archive,
            solution_dim=archive.solution_dim,
            bounds=bounds,
        )

    @property
    def sigma(self):
        """float or numpy.ndarray: Standard deviation of the (diagonal) Gaussian
        distribution when the archive is not empty."""
        return self._sigma

    @property
    def batch_size(self):
        """int: Number of solutions to return in :meth:`ask`."""
        return self._batch_size

    def ask(self):
        """Creates solutions by adding Gaussian noise to elites in the archive.

        Each solution is drawn from a distribution centered at a randomly
        chosen elite with standard deviation ``self.sigma``.
        """

        parents = self.archive.sample_elites(self._batch_size).solution_batch

        scaled_noise = self._rng.normal(
            scale=np.abs(self._sigma*(self.upper_bounds-self.lower_bounds)),
            size=(self._batch_size, self.solution_dim),
        )

        return np.clip(parents + scaled_noise, self.lower_bounds, self.upper_bounds)


class _Scheduler(Scheduler):
    """Overwwrite Scheduler to allow not using scheduler.tell"""
    
    def ask(self):

        self._last_called = "ask"
        self._solution_batch = []

        for i, emitter in enumerate(self._emitters):
            emitter_sols = emitter.ask()
            self._solution_batch.append(emitter_sols)
            self._num_emitted[i] = len(emitter_sols)

        # In case the emitters didn't return any solutions.
        self._solution_batch = np.concatenate(
            self._solution_batch, axis=0) if self._solution_batch else np.empty(
                (0, self._solution_dim))
        return self._solution_batch


    def _check_length(self, name, array):
        """Raises a ValueError if array does not have the same length as the
        solutions."""
        if len(array) != len(self._solution_batch):
            raise ValueError(
                f"{name} should have length {len(self._solution_batch)} "
                "(this is the number of solutions output by ask()) but "
                f"has length {len(array)}")

    EMPTY_WARNING = (
        "`{name}` was empty before adding solutions, and it is still empty "
        "after adding solutions. "
        "One potential cause is that `threshold_min` is too high in this "
        "archive, i.e., solutions are not being inserted because their "
        "objective value does not exceed `threshold_min`.")