"""
For better performance, all MES related
calculations are performed in this module.

Generates Parsec Coordinates to check if sample satisfies constrains
Only such "valid" samples are evaluated and added to the archive.

    - non-intersecting polynomials, 
    - non-negative y-values for upper polynomial
    - more than 1 local optimum for upper polynomial 

Candidate solutions are generated by a custom emitter class, which
adds Gaussian Noise scaled to the boundaries of solution space.

These samples are then evaluated on their
respective target objective function. 

For SAIL these are
    - Acquisition Values
    - Prediction Values



In order to generalize this function for problem domains
different than XFOIL, the generate_parsec_coordinates()
function and the codeblock checking for validity can be
removed.
"""


###### Import packages #####
from ribs.schedulers import Scheduler
from ribs.archives import GridArchive
from ribs.emitters import GaussianEmitter
from ribs.emitters._emitter_base import EmitterBase
from botorch.optim import optimize_acqf
from tqdm import tqdm
import numpy as np

##### Import custom scripts #####
from chaospy import create_sobol_samples
from xfoil.generate_airfoils import generate_parsec_coordinates
from botorch.acquisition import qLowerBoundMaxValueEntropy, qMaxValueEntropy
from utils.pprint_nd import pprint
import torch

from config.config import Config
import numpy as np
import time
config = Config('config/config.ini')
TEST_RUNS = config.TEST_RUNS
BATCH_SIZE = config.BATCH_SIZE
SIGMA_EMITTER = config.SIGMA_EMITTER
BHV_DIMENSION = config.BHV_DIMENSION
SOL_DIMENSION = config.SOL_DIMENSION
SOL_VALUE_RANGE = config.SOL_VALUE_RANGE
OBJ_BHV_NUMBER_BINS = config.OBJ_BHV_NUMBER_BINS
ACQ_BHV_NUMBER_BINS = config.ACQ_BHV_NUMBER_BINS
BHV_VALUE_RANGE = config.BHV_VALUE_RANGE
ACQ_N_MAP_EVALS = config.ACQ_N_MAP_EVALS
ACQ_MES_MIN_THRESHHOLD = config.ACQ_MES_MIN_THRESHHOLD

# MES Parameters
MES_MUTANTS = config.MES_MUTANTS
MES_GRID_SIZE = config.MES_GRID_SIZE
SIGMA_MUTANTS = config.SIGMA_MUTANTS
NUM_MV_SAMPLES = config.NUM_MV_SAMPLES
MUTANT_CELLRANGE = config.MUTANT_CELLRANGE


def mes_map_elites(self, acq_archive: GridArchive, acq_flag=False, new_elite_archive=None, new_elite_threshold=0, pred_flag=None):

    print("\n\nInitialize MES-MAP-Elites [...]")
    gp_model = self.gp_model
    n_evals = ACQ_N_MAP_EVALS

    if new_elite_archive is None: new_elite_archive = create_new_elite_archive(acq_flag=acq_flag, new_elite_threshold=new_elite_threshold)

    bhv_cellbounds_mutants, bhv_cellgrids_mutants, mes_cellgrid_mutants = mes_sobol_cellgrids(self, MUTANT_CELLRANGE)
    #bhv_cellbounds_mutants, bhv_cellgrids_mutants, mes_cellgrid_mutants = mes_sobol_cellgrids(self, mutant_cellrange=-0.00001)

    # mutants Update
    acq_elite_df = acq_archive.as_pandas(include_solutions=True)
    acq_archive.clear()
    acq_archive = update_archive(self, archive=acq_archive, gp=gp_model, candidate_sol=acq_elite_df.solution_batch(),
        bhv_cellgrid=bhv_cellgrids_mutants, 
        mes_cellgrid=mes_cellgrid_mutants, 
        bhv_cellbounds=bhv_cellbounds_mutants)

    acq_archive = optimize_mes(self, acq_archive, bhv_cellgrids_mutants, mes_cellgrid_mutants, bhv_cellbounds_mutants)

    self.visualize_archive(acq_archive, map_flag=True)

    size_t0 = acq_archive.stats.num_elites
    print(f"Acq Size: ", str(size_t0))

    start_time = time.time()
    remaining_evals = n_evals
    total_iterations = n_evals // BATCH_SIZE

    with tqdm(total=total_iterations) as progress:
        while((remaining_evals-BATCH_SIZE >= 0)):

            progress.update(1)
            valid_indices = np.empty(0, dtype=int)

            sigma_emitter = SIGMA_EMITTER + 0.45*(remaining_evals/n_evals)
            emitter = update_emitter(self, acq_archive=acq_archive, sigma_emitter=sigma_emitter)
            scheduler = _Scheduler(acq_archive, emitter)

            # Create Samples
            genomes = scheduler.ask()

            acq_archive = update_archive(self, archive=acq_archive, gp=gp_model, candidate_sol=genomes,
                bhv_cellgrid=bhv_cellgrids_mutants, 
                mes_cellgrid=mes_cellgrid_mutants, 
                bhv_cellbounds=bhv_cellbounds_mutants)

            if remaining_evals % ((n_evals)//8) == 0:

                # 1. Visualize Acquisition Archive
                # 2. Update Acquisition Archive 
                #        *before* visualisation

                if remaining_evals % ((n_evals)//4) == 0:

                    # Mutant Update
                    print(f"Mutant t_0: {np.sum(acq_archive.as_pandas().objective_batch())}")
                    acq_elite_df = acq_archive.as_pandas(include_solutions=True)
                    acq_archive = update_archive(self, archive=acq_archive, gp=gp_model, 
                        candidate_sol=acq_elite_df.solution_batch(), 
                        bhv_cellgrid=bhv_cellgrids_mutants, 
                        mes_cellgrid=mes_cellgrid_mutants, 
                        bhv_cellbounds=bhv_cellbounds_mutants)
                    print(f"Mutant t_1: {np.sum(acq_archive.as_pandas().objective_batch())}")

                self.visualize_archive(archive=acq_archive, map_flag=True)
                print(f"Acquisition Value Sum: {np.sum(acq_archive.as_pandas().objective_batch())}")

            remaining_evals -= BATCH_SIZE

        # Update Class Variable
        self.acq_archive = acq_archive

        # Remove invalid designs
        valid_indices, _ = generate_parsec_coordinates(acq_elite_df.solution_batch(), io_flag=False)
        acq_elite_df = acq_elite_df.iloc[valid_indices]
        new_elite_archive.add(acq_elite_df.solution_batch(), objective_batch=acq_elite_df.objective_batch(), measures_batch=acq_elite_df.measures_batch())

    # calculate anytime stats
    end_time = time.time()
    size_t1 = acq_archive.stats.num_elites
    print(f"\nAcq Size: ", str(size_t1))
    print(f"Map-Elites Time: {(end_time-start_time)/60} minutes")
    print("[...] End Map-Elites\n\n")
    return new_elite_archive, size_t0, size_t1


def update_archive(self, gp, archive: GridArchive, bhv_cellgrid, mes_cellgrid, bhv_cellbounds, candidate_sol):

    if candidate_sol.shape[0] == 0:
        return
    
    for i in range(0, candidate_sol.shape[0], BATCH_SIZE):

        i_candidate_sol = candidate_sol[i:i+BATCH_SIZE]

        # load cellgrids
        indices = get_cell_indices(genomes=i_candidate_sol, archive=self.acq_archive)
        _mes_cellgrids = mes_cellgrid.copy()
        _bhv_cellgrids = bhv_cellgrid[indices].copy()

        # repeat mes cellgrids then insert corresponding bhv cellgrids
        _mes_cellgrids = np.repeat(_mes_cellgrids[np.newaxis,:,:], len(indices), axis=0)
        _mes_cellgrids[:,:,1:3] = _bhv_cellgrids
        _cellbounds = bhv_cellbounds[indices].copy()

        # evaluate mes & add solutions
        solution_batch, acquisition_batch, measure_batch = acq_mes(self=self, genomes=i_candidate_sol, gp_model=gp, cellgrids=_mes_cellgrids, cellbounds=_cellbounds)
        archive.add(solution_batch, acquisition_batch, measure_batch)

    return archive


def get_cell_indices(archive, genomes):
    cell_indices = archive.index_of(genomes[:,1:3])
    genomes_behavior = genomes[:,1:3]
    genomes_cell_indices = archive.index_of(genomes_behavior)
    return genomes_cell_indices


def update_emitter(self, acq_archive, sigma_emitter=SIGMA_EMITTER, sol_value_range=SOL_VALUE_RANGE):

    self.update_seed()

    emitter = [
        ScaledGaussianEmitter(
        archive=acq_archive,
        sigma=sigma_emitter,
        bounds= np.array(sol_value_range),
        batch_size=BATCH_SIZE,
        seed=self.current_seed
    )]

    return emitter


class ScaledGaussianEmitter(GaussianEmitter):

    """
    Custom Emitter class
        - Adds Gaussian Noise scaled to solution space boundaries
        - Requires filled archive instead of initial solutions
    """

    def __init__(self,
                 archive,
                 *,
                 sigma,
                 bounds=None,
                 batch_size=BATCH_SIZE,
                 seed=None):

        self._rng = np.random.default_rng(seed)
        self._batch_size = batch_size
        self._sigma = np.array(sigma, dtype=archive.dtype)

        if archive.stats.num_elites == 0:
            raise ValueError("Archive must be filled with initial solutions.")

        EmitterBase.__init__(
            self,
            archive,
            solution_dim=archive.solution_dim,
            bounds=bounds,
        )

    @property
    def sigma(self):
        """float or numpy.ndarray: Standard deviation of the (diagonal) Gaussian
        distribution when the archive is not empty."""
        return self._sigma

    @property
    def batch_size(self):
        """int: Number of solutions to return in :meth:`ask`."""
        return self._batch_size

    def ask(self):
        """Creates solutions by adding Gaussian noise to elites in the archive.

        Each solution is drawn from a distribution centered at a randomly
        chosen elite with standard deviation ``self.sigma``.
        """

        parents = self.archive.sample_elites(self._batch_size).solution_batch

        scaled_noise = self._rng.normal(
            scale=np.abs(self._sigma*(self.upper_bounds-self.lower_bounds)),
            size=(self._batch_size, self.solution_dim),
        )

        return np.clip(parents + scaled_noise, self.lower_bounds, self.upper_bounds)


class _Scheduler(Scheduler):
    """Overwwrite Scheduler to allow not using scheduler.tell"""
    
    def ask(self):

        self._last_called = "ask"
        self._solution_batch = []

        for i, emitter in enumerate(self._emitters):
            emitter_sols = emitter.ask()
            self._solution_batch.append(emitter_sols)
            self._num_emitted[i] = len(emitter_sols)

        # In case the emitters didn't return any solutions.
        self._solution_batch = np.concatenate(
            self._solution_batch, axis=0) if self._solution_batch else np.empty(
                (0, self._solution_dim))
        return self._solution_batch


    def _check_length(self, name, array):
        """Raises a ValueError if array does not have the same length as the
        solutions."""
        if len(array) != len(self._solution_batch):
            raise ValueError(
                f"{name} should have length {len(self._solution_batch)} "
                "(this is the number of solutions output by ask()) but "
                f"has length {len(array)}")

    EMPTY_WARNING = (
        "`{name}` was empty before adding solutions, and it is still empty "
        "after adding solutions. "
        "One potential cause is that `threshold_min` is too high in this "
        "archive, i.e., solutions are not being inserted because their "
        "objective value does not exceed `threshold_min`.")
    

def create_new_elite_archive(acq_flag=False, new_elite_archive=None, new_elite_threshold=0, pred_flag=None):

    number_bins = ACQ_BHV_NUMBER_BINS if acq_flag else OBJ_BHV_NUMBER_BINS

    new_elite_archive = GridArchive(
        solution_dim=SOL_DIMENSION,
        dims=number_bins,
        ranges=BHV_VALUE_RANGE,
        qd_score_offset=-600,
        threshold_min = new_elite_threshold,)
    
    return new_elite_archive
