"""
For better performance, all MES related
calculations are performed in this module.

Generates Parsec Coordinates to check if sample satisfies constrains
Only such "valid" samples are evaluated and added to the archive.

    - non-intersecting polynomials, 
    - non-negative y-values for upper polynomial
    - more than 1 local optimum for upper polynomial 

Candidate solutions are generated by a custom emitter class, which
adds Gaussian Noise scaled to the boundaries of solution space.

These samples are then evaluated on their
respective target objective function. 

For SAIL these are
    - Acquisition Values
    - Prediction Values

In order to generalize this function for problem domains
different than XFOIL, the generate_parsec_coordinates()
function and the codeblock checking for validity can be
removed.
"""


###### Import packages #####
from ribs.schedulers import Scheduler
from ribs.archives import GridArchive
from ribs.emitters import GaussianEmitter
from ribs.emitters._emitter_base import EmitterBase
from chaospy import create_sobol_samples
from botorch.acquisition import qLowerBoundMaxValueEntropy, qMaxValueEntropy
from botorch.optim import optimize_acqf
from tqdm import tqdm
import numpy as np

##### Import custom scripts #####
from xfoil.generate_airfoils import generate_parsec_coordinates
from utils.pprint_nd import pprint
import torch
from config.config import Config
import numpy as np
import time
config = Config('config/config.ini')
TEST_RUNS = config.TEST_RUNS
BATCH_SIZE = config.BATCH_SIZE
SIGMA_EMITTER = config.SIGMA_EMITTER
BHV_DIMENSION = config.BHV_DIMENSION
SOL_DIMENSION = config.SOL_DIMENSION
SOL_VALUE_RANGE = config.SOL_VALUE_RANGE
OBJ_BHV_NUMBER_BINS = config.OBJ_BHV_NUMBER_BINS
ACQ_BHV_NUMBER_BINS = config.ACQ_BHV_NUMBER_BINS
BHV_VALUE_RANGE = config.BHV_VALUE_RANGE
ACQ_N_MAP_EVALS = config.ACQ_N_MAP_EVALS

# MES Parameters
MES_MUTANTS = config.MES_MUTANTS
MES_GRID_SIZE = config.MES_GRID_SIZE
SIGMA_MUTANTS = config.SIGMA_MUTANTS
NUM_MV_SAMPLES = config.NUM_MV_SAMPLES
MUTANT_CELLRANGE = config.MUTANT_CELLRANGE


def mes_map_elites(self, acq_archive: GridArchive, acq_flag=None, pred_flag=None):

    print("\n\nInitialize MES-MAP-Elites [...]")
    gp_model = self.gp_model
    n_evals = ACQ_N_MAP_EVALS

    bhv_cellbounds_mutants, bhv_cellgrids_mutants, mes_cellgrid_mutants = mes_sobol_cellgrids(self, MUTANT_CELLRANGE)
    bhv_cellbounds_restricted, bhv_cellgrids_restricted, mes_cellgrid_restricted = mes_sobol_cellgrids(self, mutant_cellrange=-0.00001)

    # mutants Update
    acq_elite_df = acq_archive.as_pandas(include_solutions=True)
    acq_archive.clear()
    acq_archive = update_archive(self, archive=acq_archive, gp=gp_model, candidate_sol=acq_elite_df.solution_batch(),
        bhv_cellgrid=bhv_cellgrids_restricted, 
        mes_cellgrid=mes_cellgrid_restricted, 
        bhv_cellbounds=bhv_cellbounds_restricted)

    acq_archive = optimize_mes(self, acq_archive, bhv_cellgrids_mutants, mes_cellgrid_mutants, bhv_cellbounds_mutants)

    acq_elite_df = acq_archive.as_pandas(include_solutions=True)
    acq_archive.clear()
    acq_archive = update_archive(self, archive=acq_archive, gp=gp_model, candidate_sol=acq_elite_df.solution_batch(),
        bhv_cellgrid=bhv_cellgrids_mutants, 
        mes_cellgrid=mes_cellgrid_mutants, 
        bhv_cellbounds=bhv_cellbounds_mutants)

    size_t0 = acq_archive.stats.num_elites
    print(f"Acq Size: ", str(size_t0))

    start_time = time.time()
    remaining_evals = n_evals
    total_iterations = n_evals // BATCH_SIZE

    with tqdm(total=total_iterations) as progress:
        while((remaining_evals-BATCH_SIZE >= 0)):

            progress.update(1)

            sigma_emitter = SIGMA_EMITTER + 0.15*(remaining_evals/n_evals)
            emitter = update_emitter(self, acq_archive=acq_archive, sigma_emitter=sigma_emitter)
            scheduler = _Scheduler(acq_archive, emitter)

            # Create Samples
            genomes = scheduler.ask()

            valid_indices, _ = generate_parsec_coordinates(genomes, io_flag=False)

            acq_archive = update_archive(self, archive=acq_archive, gp=gp_model, candidate_sol=genomes[valid_indices],
                bhv_cellgrid=bhv_cellgrids_mutants, 
                mes_cellgrid=mes_cellgrid_mutants,
                bhv_cellbounds=bhv_cellbounds_mutants)

            if remaining_evals % ((n_evals)//8) == 0:

                # 1. Visualize Acquisition Archive
                # 2. Update Acquisition Archive 
                #        *before* visualisation

                if remaining_evals % ((n_evals)//4) == 0:

                    # Mutant Update
                    print(f"Mutant t_0: {np.sum(acq_archive.as_pandas().objective_batch())}")
                    acq_elite_df = acq_archive.as_pandas(include_solutions=True)
                    valid_indices, _ = generate_parsec_coordinates(acq_elite_df.solution_batch(), io_flag=False)
                    acq_elite_df = acq_elite_df.iloc[valid_indices]
                    acq_archive.clear()
                    acq_archive = update_archive(self, archive=acq_archive, gp=gp_model, 
                        candidate_sol=acq_elite_df.solution_batch(), 
                        bhv_cellgrid=bhv_cellgrids_restricted, 
                        mes_cellgrid=mes_cellgrid_restricted, 
                        bhv_cellbounds=bhv_cellbounds_restricted)
                    print(f"Mutant t_1: {np.sum(acq_archive.as_pandas().objective_batch())}")
                self.visualize_archive(archive=acq_archive, map_flag=True)

            remaining_evals -= BATCH_SIZE

    # calculate anytime stats
    end_time = time.time()
    size_t1 = acq_archive.stats.num_elites
    print(f"\nAcq Size: ", str(size_t1))
    print(f"Map-Elites Time: {(end_time-start_time)/60} minutes")
    print("[...] End Map-Elites\n\n")
    return size_t0, size_t1


def acq_mes(self, archive, gp_model, genomes, cellgrids, cellbounds):

    rng = np.random.default_rng(self.current_seed)

    solutionbounds = np.array(SOL_VALUE_RANGE)
    cell_solutionbounds = np.repeat(solutionbounds[np.newaxis,:,:], len(genomes), axis=0)
    cell_solutionbounds[:, 1:3] = cellbounds

    # Generate n=MES_MUTANTS using Gaussian Noise
    genomes = np.repeat(genomes, MES_MUTANTS, axis=0).reshape(len(genomes), MES_MUTANTS, SOL_DIMENSION)
   
    for i in range(len(genomes)):
        scaled_noise = rng.normal(
                            scale=np.abs(SIGMA_MUTANTS *(cell_solutionbounds[i,:,1] - cell_solutionbounds[i,:,0])), 
                            size=(MES_MUTANTS, SOL_DIMENSION))

        genomes[i] = np.clip(genomes[i] + scaled_noise, cell_solutionbounds[i,:,0], cell_solutionbounds[i,:,1])
        if np.isnan(genomes[i]).any(): raise ValueError("NaN in genomes")

    acq_entropy = torch.tensor([])
    cellgrids_tensor = torch.tensor(cellgrids)
    genomes_tensor = torch.tensor(genomes)

    # calculate MES for each mutant batch & select best mutant
    for i in range(genomes.shape[0]):

        i_genomes = genomes_tensor[i]
        i_transformed_genomes = i_genomes.unsqueeze(1)
        MES = qLowerBoundMaxValueEntropy(model=gp_model, candidate_set=cellgrids_tensor[i], num_mv_samples=NUM_MV_SAMPLES)
        #MES = qMaxValueEntropy(model=gp_model, candidate_set=cellgrids_tensor[i], num_mv_samples=NUM_MV_SAMPLES, num_y_samples=64, num_fantasies=2)
        i_acq_entropy_tensor = MES(i_transformed_genomes)
        acq_entropy = torch.cat((acq_entropy, i_acq_entropy_tensor))

    genomes = genomes.reshape(-1, SOL_DIMENSION)
    return genomes, acq_entropy.detach().numpy(), genomes[:,1:3]



def optimize_mes(self, acq_archive, bhv_cellgrid, mes_cellgrid, bhv_cellbounds):

    np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

    gp_model = self.gp_model
    n_bins = np.prod(acq_archive.dims)
    n_samples = n_bins // 16

    acq_elite_df = acq_archive.as_pandas(include_solutions=True)
    acq_elite_df = acq_elite_df.sample(frac=1, random_state=self.current_seed)  # shuffle elites
    acq_elite_df = acq_elite_df.head(n=n_samples)                               # sample elites

    print("\nOptimize MES: n_samples", n_samples)

    sum_perc_improvement = 0

    genomes = acq_elite_df.solution_batch()
    objectives = acq_elite_df.objective_batch()

    cell_indices = acq_archive.index_of(genomes[:,1:3])

    _mes_cellgrids = mes_cellgrid.copy()
    _mes_cellgrids = np.repeat(_mes_cellgrids[np.newaxis,:,:], len(cell_indices), axis=0)
    _bhv_cellgrids = bhv_cellgrid[cell_indices].copy()
    _mes_cellgrids[:,:,1:3] = _bhv_cellgrids
    _cellbounds = bhv_cellbounds[cell_indices].copy()

    solutionbounds = np.array(SOL_VALUE_RANGE)
    cell_solutionbounds = np.repeat(solutionbounds[np.newaxis,:,:], len(genomes), axis=0)    # create copies of solutionbounds
    cell_solutionbounds[:, 1:3] = _cellbounds                                                # insert niche-specific cellbounds

    # track time
    import time
    start = time.time()

    new_genomes = np.empty((n_samples, SOL_DIMENSION))
    new_acquisitions = np.empty((n_samples, 1))

    # optimize MES for each mutant batch & select best mutant
    for i in range(genomes.shape[0]):

        _mes_cellgrid = torch.tensor(_mes_cellgrids[i], dtype=torch.float64)      # Shape: MES_GRIDSIZE x SOL_DIMENSION
        MES = qLowerBoundMaxValueEntropy(model=gp_model, candidate_set=_mes_cellgrid, num_mv_samples=NUM_MV_SAMPLES)
        #MES = qMaxValueEntropy(model=gp_model, candidate_set=_mes_cellgrid, num_mv_samples=NUM_MV_SAMPLES, num_y_samples=64, num_fantasies=2)

        new_genome, new_acquisition = optimize_acqf(
            acq_function=MES,
            bounds=torch.tensor(cell_solutionbounds[i].T, dtype=torch.float64),
            q=1,
            num_restarts=10,
            raw_samples=1024,
            #batch_initial_conditions=genomes_tensor[i].unsqueeze(0) 
        )

        new_genome = new_genome.detach().numpy()
        new_acquisition = new_acquisition.detach().numpy()

        new_acquisitions[i] = new_acquisition
        new_genomes[i] = new_genome

        perc_improvement = ((new_acquisition)-objectives[i])/objectives[i] * 500
        sum_perc_improvement += perc_improvement
        print("MES SAIL: {:.3f}  botorch.optimize_acqf(): {:.3f}  Improvement (Percent): {:.3f}".format(objectives[i], new_acquisition, perc_improvement))

    acq_archive = update_archive(self, archive=acq_archive, gp=gp_model, candidate_sol=new_genomes, 
        bhv_cellgrid=bhv_cellgrid,
        mes_cellgrid=mes_cellgrid,
        bhv_cellbounds=bhv_cellbounds)

    mean_perc_improvement = sum_perc_improvement / n_samples
    print("Mean Improvement (Percent): ", mean_perc_improvement)
    print("Optimize MES Time: ", time.time() - start)

    return acq_archive


def mes_sobol_cellgrids(self, mutant_cellrange, cell_indices=None):
    """Included in this module only for efficienty - detailled documentation in acq_functions/acq_mes.py"""

    sobol_cellgrid = create_sobol_samples(order=MES_GRID_SIZE, dim=SOL_DIMENSION, seed=self.current_seed).T

    archive = self.acq_archive

    if cell_indices is None:
        n_cells = np.prod(archive.dims)
        archive_indices = range(n_cells)
        idx = archive.int_to_grid_index(archive_indices)
    else:
        n_cells = cell_indices.shape[0]
        idx = archive.int_to_grid_index(cell_indices)

    lower_bounds = np.array(SOL_VALUE_RANGE)[:, 0]
    upper_bounds = np.array(SOL_VALUE_RANGE)[:, 1]

    bhv_cellgrid = sobol_cellgrid[:, 1:3]
    mes_cellgrid = sobol_cellgrid * (upper_bounds - lower_bounds) + lower_bounds

    boundaries_0 = archive.boundaries[0]
    boundaries_1 = archive.boundaries[1]

    cell_range_0 = np.diff(boundaries_0)[0]
    cell_range_1 = np.diff(boundaries_1)[0]

    # 625 bins, MES_GRID_SIZE samples, 2 dimensions
    bhv_cellgrids = np.empty((n_cells, MES_GRID_SIZE, BHV_DIMENSION))
    bhv_cellbounds = np.empty((n_cells, BHV_DIMENSION, 2))

    for i in range(n_cells):

        measure_0_idx, measure_1_idx = idx[i]

        # Allow mutants by scaling cellbounds
        cell_bounds_0 = (boundaries_0[measure_0_idx] - cell_range_0*mutant_cellrange,
                         boundaries_0[measure_0_idx+1] + cell_range_0*mutant_cellrange)

        cell_bounds_1 = (boundaries_1[measure_1_idx] - cell_range_1*mutant_cellrange,
                         boundaries_1[measure_1_idx+1] + cell_range_1*mutant_cellrange)

        # Restrict cellbounds to solution space boundaries
        cell_bounds_0 = np.clip(cell_bounds_0, boundaries_0[0], boundaries_0[-1])
        cell_bounds_1 = np.clip(cell_bounds_1, boundaries_1[0], boundaries_1[-1])

        cell_bounds_i = np.array([cell_bounds_0, cell_bounds_1])
        bhv_cellbounds[i] = cell_bounds_i

        lower_bounds = cell_bounds_i[:, 0]
        upper_bounds = cell_bounds_i[:, 1]
        cell_bound_ranges = upper_bounds - lower_bounds

        bhv_cellgrid_i = bhv_cellgrid.copy()        
        bhv_cellgrid_i = bhv_cellgrid_i * cell_bound_ranges.T + lower_bounds   # scale sobol cellgrid to cellbounds
        bhv_cellgrids[i] = bhv_cellgrid_i                                      # insert bhv cellgrid into mes cellgrid

    return bhv_cellbounds, bhv_cellgrids, mes_cellgrid


def update_archive(self, gp, archive: GridArchive, bhv_cellgrid, mes_cellgrid, bhv_cellbounds, candidate_sol):

    acq_sum_t0 = np.sum(archive.as_pandas().objective_batch())
    acq_t0_df = archive.as_pandas(include_solutions=True).sort_index()

    if candidate_sol.shape[0] == 0:
        return
    
    for i in range(0, candidate_sol.shape[0], BATCH_SIZE):

        i_candidate_sol = candidate_sol[i:i+BATCH_SIZE]

        # load cellgrids
        indices = get_cell_indices(genomes=i_candidate_sol, archive=self.acq_archive)
        _mes_cellgrids = mes_cellgrid.copy()
        _bhv_cellgrids = bhv_cellgrid[indices].copy()

        # repeat mes cellgrids then insert corresponding bhv cellgrids
        _mes_cellgrids = np.repeat(_mes_cellgrids[np.newaxis,:,:], len(indices), axis=0)
        _mes_cellgrids[:,:,1:3] = _bhv_cellgrids
        _cellbounds = bhv_cellbounds[indices].copy()

        # evaluate mes & add solutions
        solution_batch, acquisition_batch, measure_batch = acq_mes(self=self, archive=archive, genomes=i_candidate_sol, gp_model=gp, cellgrids=_mes_cellgrids, cellbounds=_cellbounds)
        
        archive.add(solution_batch, acquisition_batch, measure_batch)

    acq_sum_t1 = np.sum(archive.as_pandas().objective_batch())
    acq_t1_df = archive.as_pandas(include_solutions=True).sort_index()

    if acq_sum_t0 > acq_sum_t1:
        acq_t1_df = acq_t1_df.assign(objective_difference=acq_t1_df.objective_batch() - acq_t0_df.objective_batch())
        acq_t1_df = acq_t1_df.assign(objective_increase=(acq_t1_df.objective_batch() / acq_t0_df.objective_batch()) - 1)
        raise ValueError("acq_sum_t0 < acq_sum_t1")

    return archive


def get_cell_indices(archive, genomes):
    cell_indices = archive.index_of(genomes[:,1:3])
    genomes_behavior = genomes[:,1:3]
    genomes_cell_indices = archive.index_of(genomes_behavior)
    return genomes_cell_indices


def update_emitter(self, acq_archive, sigma_emitter=SIGMA_EMITTER, sol_value_range=SOL_VALUE_RANGE):

    self.update_seed()

    emitter = [
        ScaledGaussianEmitter(
        archive=acq_archive,
        sigma=sigma_emitter,
        bounds= np.array(sol_value_range),
        batch_size=BATCH_SIZE,
        seed=self.current_seed
    )]

    return emitter


class ScaledGaussianEmitter(GaussianEmitter):

    """
    Custom Emitter class
        - Adds Gaussian Noise scaled to solution space boundaries
        - Requires filled archive instead of initial solutions
    """

    def __init__(self,
                 archive,
                 *,
                 sigma,
                 bounds=None,
                 batch_size=BATCH_SIZE,
                 seed=None):

        self._rng = np.random.default_rng(seed)
        self._batch_size = batch_size
        self._sigma = np.array(sigma, dtype=archive.dtype)

        if archive.stats.num_elites == 0:
            raise ValueError("Archive must be filled with initial solutions.")

        EmitterBase.__init__(
            self,
            archive,
            solution_dim=archive.solution_dim,
            bounds=bounds,
        )

    @property
    def sigma(self):
        """float or numpy.ndarray: Standard deviation of the (diagonal) Gaussian
        distribution when the archive is not empty."""
        return self._sigma

    @property
    def batch_size(self):
        """int: Number of solutions to return in :meth:`ask`."""
        return self._batch_size

    def ask(self):
        """Creates solutions by adding Gaussian noise to elites in the archive.

        Each solution is drawn from a distribution centered at a randomly
        chosen elite with standard deviation ``self.sigma``.
        """

        parents = self.archive.sample_elites(self._batch_size).solution_batch

        scaled_noise = self._rng.normal(
            scale=np.abs(self._sigma*(self.upper_bounds-self.lower_bounds)),
            size=(self._batch_size, self.solution_dim),
        )

        return np.clip(parents + scaled_noise, self.lower_bounds, self.upper_bounds)


class _Scheduler(Scheduler):
    """Overwwrite Scheduler to allow not using scheduler.tell"""
    
    def ask(self):

        self._last_called = "ask"
        self._solution_batch = []

        for i, emitter in enumerate(self._emitters):
            emitter_sols = emitter.ask()
            self._solution_batch.append(emitter_sols)
            self._num_emitted[i] = len(emitter_sols)

        # In case the emitters didn't return any solutions.
        self._solution_batch = np.concatenate(
            self._solution_batch, axis=0) if self._solution_batch else np.empty(
                (0, self._solution_dim))
        return self._solution_batch


    def _check_length(self, name, array):
        """Raises a ValueError if array does not have the same length as the
        solutions."""
        if len(array) != len(self._solution_batch):
            raise ValueError(
                f"{name} should have length {len(self._solution_batch)} "
                "(this is the number of solutions output by ask()) but "
                f"has length {len(array)}")

    EMPTY_WARNING = (
        "`{name}` was empty before adding solutions, and it is still empty "
        "after adding solutions. "
        "One potential cause is that `threshold_min` is too high in this "
        "archive, i.e., solutions are not being inserted because their "
        "objective value does not exceed `threshold_min`.")