[INTEGER]
ACQ_N_OBJ_EVALS = 1000
ACQ_N_MAP_EVALS = 200
PRED_N_EVALS = 200
PARALLEL_BATCH_SIZE = 10
INIT_ARCHIVE_SIZE = 10
OBJ_DIMENSION = 1
SOL_DIMENSION = 12

[ARRAYS]
BHV_ARCHIVE_DIMENSION = [2]
BHV_NUMBER_BINS = [25,25]

[TUPLE_ARRAYS]
BHV_DIMENSION = 2
BHV_VALUE_RANGE = [(0,1), (0,1)]
# copied from /sail/domains/parsec/airFoiltools/encoding/parsec_Domain
#                       rLeUp               Xup                 Zup            Z_XXup           rLeLo           Xlo              Zlo                Z_XXlo               Z_Te          dZ_Te           a_Te            b_Te
SOL_VALUE_RANGE = [(0.00375 , 0.05), (0.2625 , 0.6875), (0.0725 , 0.1875), (-0.75 , 0.25), (0.005 , 0.04), (0.300 , 0.6), (-0.012 , -0.05875), (-0.81  , -0.375), (0.001 , 0.001), (-0.00, 0.01), (-6.0, -2.0125), (2.5, 11.413)]
