[INTEGER]
ACQ_N_MAP_EVALS = 8000
ACQ_N_OBJ_EVALS = 700
PRED_N_MAP_EVALS = 500000
PRED_N_OBJ_EVALS = 400
PREDICTION_VERIFICATIONS = 20
INIT_N_EVALS = 40
INIT_N_ACQ_EVALS = 100
TEST_RUNS = 5
N_XY_COORDINATES = 160
BATCH_SIZE = 10
OBJ_DIMENSION = 1
BHV_DIMENSION = 2
SOL_DIMENSION = 11
REYNOLDS = 1000000
# for proper functionality of anytime_archive_visualizer.py, MAX_PRED_VERIFICATION+ACQ_N_OBJ_EVALS+INIT_N_EVALS needs to be a multiple of BATCH_SIZE*8*(2^n) - buffering behavior can be modified inside the module

[ARRAYS]
BHV_ARCHIVE_DIMENSION = [2]
BHV_NUMBER_BINS = [25,25]

[TUPLE_ARRAYS]
# Xup & Zup are used as bhv values for the airfoil's upper surface
# copied from https://github.com/agaier/sail:    /sail/domains/parsec/airFoiltools/encoding/parsec_Domain         dZ_TE has been removed from the searchspace, as it presents a constant value and can be hardcoded into generate_airfoils.py
#                      1 rLeUp            2 Xup              3 Zup           4 Z_XXup         5 rLeLo          6 Xlo              7 Zlo               8 Z_XXlo        9 dZ_Te         10 Z_Te         11 a_Te           12 b_Te
SOL_VALUE_RANGE = [(0.00375 , 0.05), (0.2625 , 0.6875), (0.0725 , 0.1875), (-0.75 , 0.25), (0.005 , 0.04), (0.300 , 0.6), (-0.05875, -0.012), (-0.81  , -0.375),                  (-0.00, 0.01), (-6.0, -2.0125), (2.5, 11.413)] 
BHV_DIMENSION = 2
BHV_VALUE_RANGE = [(0.2625,0.6875), (0.0725,0.1875)]

[FLOAT]
ALFA = 2.7
MACH = 0.5
SIGMA_UCB = 0.5
SIGMA_EMITTER = 0.28
OBJ_MIN_THRESHHOLD = 1.8
ACQ_UCB_MIN_THRESHHOLD = 1.5
ACQ_MES_MIN_THRESHHOLD = 0.00001